In [1]:
import pandas as pd
import numpy
from sklearn import linear_model



In [2]:
df=pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
model=linear_model.LinearRegression()
model.fit(df[["area"]],df.price)

LinearRegression()

In [6]:
model.coef_


array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

array([859554.79452055])

In [9]:
import pickle

In [10]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)
# Save Model To a File Using Python Pickle
# All that model saves as parameters for example if using linear regression
# it will save the value of m and b. Because that is enough to do predictions.Dataframe will not be saved

In [11]:
with open('model_pickle','rb') as file:
    mp=pickle.load(file)

In [12]:
mp.predict([[5000]])
# same ans

array([859554.79452055])

In [13]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Program Files\Python39\lib\site-packages\sklearn\externals\__init__.py)

In [14]:
import joblib as joblib

In [16]:
joblib.dump(model,"model_joblib")
# save it as a model

['model_joblib']

In [18]:
mj=joblib.load('model_joblib')
mj
# again load it from there.....joblib is preferred when ur numpy array is too huge..that is in real life scenario

LinearRegression()

In [19]:
mj.predict([[5000]])

array([859554.79452055])

In [20]:
mj.intercept_

180616.43835616432