In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data, digits.target,test_size=0.3)
# now here in test_split model you get different values every single time and with this...
# the efficinecy in all the 3 cases changes
print(len(digits.data))

1797


In [7]:
# LOGISTIC REGRESSION
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9425925925925925

In [8]:
# SUPPORT VECTOR MACHINE
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3962962962962963

In [9]:
# RANDOM FOREST
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9629629629629629

In [10]:
# so many times u will be confused which model to follow
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)
# here after splitting it 

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [13]:

def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [14]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)
# in KFold stratifiedKFold is better option

In [34]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=3000),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))    
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test)) 
    
#  if u dont want to write this much big code refer "cross_val_score"

In [35]:
scores_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [36]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [37]:
scores_rf

[0.9181969949916527, 0.9632721202003339, 0.9265442404006677]

In [41]:
from sklearn.model_selection import cross_val_score
print(len(digits.target))

1797


In [42]:
cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [43]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [44]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.93333333, 0.89722222, 0.94986072, 0.96935933, 0.90529248])

In [45]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target)
# with increasing n_estimators the success rate is increasing too much....after a point it will fall down

array([0.93333333, 0.92777778, 0.95543175, 0.95543175, 0.93036212])

In [47]:
cross_val_score(RandomForestClassifier(n_estimators=80),digits.data,digits.target)

array([0.93333333, 0.90833333, 0.96100279, 0.96100279, 0.93314763])